name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Cache cargo bin
      uses: actions/cache@v1
      with:
        path: ~/.cargo/bin
        key: ${{ runner.os }}-cargo-bin
    - name: Install cross
      # run: curl -LSfs https://japaric.github.io/trust/install.sh | sh -s -- --git rust-embedded/cross --force
      run: which cross || cargo install cross
    - name: Install cargo deb
      run: which cargo-deb || cargo install cargo-deb
    - name: Build Package
      run: make package
